#!/usr/bin/env bash
# Quick Supabase Database Setup

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         Supabase Database Initialization Guide                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Your tables are NOT yet created in Supabase."
echo ""
echo "⏱️  This will take ~2 minutes. Follow these steps:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1️⃣  - Open SQL Editor in Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  👉 Click this link to open Supabase SQL Editor:"
echo ""
echo "  https://app.supabase.com/project/jdvbjkidxvpysmcnbreb/sql/new"
echo ""
echo ""
echo "STEP 2️⃣  - Copy the migration SQL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📄 The SQL file is located at:"
echo "     supabase/migrations/001_create_tables.sql"
echo ""
echo "  Or view it here:"
cat << 'SQL'
     ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼

     Open supabase/migrations/001_create_tables.sql 
     and copy ALL the content

     ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
SQL
echo ""
echo ""
echo "STEP 3️⃣  - Paste into Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. In the Supabase SQL Editor (opened in Step 1)"
echo "  2. Clear the default comment"
echo "  3. Paste the entire SQL migration"
echo ""
echo ""
echo "STEP 4️⃣  - Run the SQL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🚀 Press: Ctrl+Enter  OR  Click the Run button (▶️)"
echo ""
echo "  ✅ Wait for all queries to complete (shows green checkmarks)"
echo ""
echo ""
echo "STEP 5️⃣  - Create a test user (after step 4 completes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Run this command in your terminal:"
echo ""
echo "    source <(grep -v '^#' .env.local) && node scripts/create-user.js"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❓ Need help? Check: DATABASE_SETUP.md"
echo ""
